name: Publish Helm Chart to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for full history for gh-pages

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Package Helm chart
        run: |
          mkdir -p packaged
          helm package charts/vulnerabilityslo --destination packaged

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy packaged chart to gh-pages
        run: |
          cp packaged/*.tgz gh-pages/

      - name: Update Helm repo index
        run: |
          cd gh-pages
          helm repo index . --url https://vulnerabilityslo.github.io/helm-charts
        env:
          HELM_EXPERIMENTAL_OCI: 1

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Publish Helm chart from ${{ github.sha }}" || echo "No changes to commit"
          git push origin gh-pages
